expressions:
  - name: neutral
    filename: 1f610
    dofs: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
  - name: happy
    filename: 1f642
    poly: 1
  - name: laughing
    filename: 1f603
    poly: 3
  - name: surprised
    filename: 1f62f
    poly: 5
  - name: afraid
    filename: 1f616
    poly: 7
  - name: angry
    filename: 1f620
    poly: 8
  - name: disgusted
    filename: 1f623
    poly: 10
  - name: sad
    filename: 1f641
    poly: 11
  - name: tired
    filename: 1f614
    poly: 15
  - name: sleep
    filename: 1f634
    dofs: [ 0, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0 ]
