modules:
  - name: eyebrow left
    type: turn
    grid:
      x: 18
      y: 5
      rotation: 0
    dofs:
      - name: rotation
        servo:
          pin: 11
          mid: 1500
          min: 300
          max: -300
        mapping:
          neutral: 0
          poly: [ 0.3, 0.5, 0.7, 0.5, 0.15, -0.15, -0.45, -0.7, -1, -0.65, -0.35, 0, 0.25, 0.5, 0.5, 0.45, 0.75, 1, 0.7, 0.25 ]

  - name: eye left
    type: eye
    grid:
      x: 17
      y: 10
      rotation: 0
    dofs:
      - name: horizontal
        servo:
          pin: 15
          mid: 1500
          min: 300
          max: -300
        mapping:
          neutral: 0
          poly: [ 0, 0, 0, 0, 0, 0.6, 0.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, -0.35, -0.25, 0, 0 ]
      - name: vertical
        servo:
          pin: 14
          mid: 1500
          min: -300
          max: 300
        mapping:
          neutral: 0
          poly: [ 0, 0, 0, 0, 0, 0, 0, 0, -0.3, -0.5, -0.7, -0.5, -0.4, 0, 0, 0, 0, 0, 0, 0 ]
      - name: lid
        servo:
          pin: 13
          mid: 1300
          min: -400
          max: 450
        mapping:
          neutral: 0.7
          poly: [ 0.7, 1, 1, 0.65, 0.25, 0, 0.05, -0.05, 0, -0.05, -0.15, -0.35, -0.65, -1, -0.45, -0.15, 0.15, 0.4, 0.5, 0.5 ]

  - name: mouth
    type: mouth
    grid:
      x: 12
      y: 20
      rotation: 0
    dofs:
      - name: rotation left
        servo:
          pin: 10
          mid: 1500
          min: -250
          max: 250
        mapping:
          neutral: 0
          poly: [ 0.5, 0.75, 1, 0.6, 0.1, -0.3, -0.55, 0.5, -0.5, -0.4, -0.25, -0.15, -0.15, -0.25, -0.55, -0.1, 0.15, 0.25, 0.2, 0.35 ]

      - name: rotation right
        servo:
          pin: 5
          mid: 1500
          min: 250
          max: -250
        mapping:
          neutral: 0
          poly: [ 0.5, 0.75, 1, 0.6, 0.1, -0.3, -0.7, -1, -0.75, -0.4, -0.25, -0.15, -0.15, -0.25, -0.1, -0.1, 0.15, 0.25, 0.2, 0.35 ]

  - name: eye right
    type: eye
    grid:
      x: 7
      y: 10
      rotation: 0
    dofs:
      - name: horizontal
        servo:
          pin: 0
          mid: 1500
          min: 300
          max: -300
        mapping:
          neutral: 0
          poly: [ 0, 0, 0, 0, 0, -0.6, -0.4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.35, 0.25, 0, 0 ]
      - name: vertical
        servo:
          pin: 1
          mid: 1500
          min: -300
          max: 300
        mapping:
          neutral: 0
          poly: [ 0, 0, 0, 0, 0, 0, 0, 0, -0.3, -0.5, -0.7, -0.5, -0.4, 0, 0, 0, 0, 0, 0, 0 ]
      - name: lid
        servo:
          pin: 2
          mid: 1300
          min: -400
          max: 450
        mapping:
          neutral: 0.7
          poly: [ 0.7, 1, 1, 0.65, 0.25, 0, 0.05, -0.05, 0, -0.05, -0.15, -0.35, -0.65, -1, -0.45, -0.15, 0.15, 0.4, 0.5, 0.5 ]

  - name: eyebrow right
    type: turn
    grid:
      x: 6
      y: 5
      rotation: 180
    dofs:
      - name: rotation
        servo:
          pin: 4
          mid: 1500
          min: 300
          max: -300
        mapping:
          neutral: 0
          poly: [ -0.3, -0.5, -0.7, -0.5, -0.15, 0.15, 0.45, 0.7, 1, 0.65, 0.35, 0, -0.25, -0.5, -0.5, -0.45, -0.75, -1, -0.7, -0.25 ]

  - name: speaker
    type: speaker
    grid:
      x: 12
      y: 27
      rotation: 0

  - name: heart
    type: heart
    grid:
      x: 12
      y: 33
      rotation: 0
