audio:
  master_volume: 100
  tts_engine: espeak
  tts_gender: m
  tts_language: en
behaviour:
  blink: false
  caffeine: 0
  enabled: false
  gaze: true
general:
  robot_name: robot
  startup_app: --None--
security:
  password: opsoro123
wireless:
  channel: 6
  password: RobotOpsoro
  ssid: OPSORO-bot
