#!/bin/sh

# stop opsoro service
# backup all files to seperate location (GIT pull is safe enough, we only keep this in case the user wants to revert)
# git pull
# restart opsoro service


sudo service opsoro stop

sudo mkdir /home/pi/software/previous/
sudo cp -r /home/pi/software/OPSORO-software/ /home/pi/software/previous/OPSORO-software/

sudo git --git-dir=/home/pi/software/.git/ --work-tree=/home/pi/software/ remote update
sudo git --git-dir=/home/pi/software/.git/ --work-tree=/home/pi/software/ pull

#sudo chmod +x /home/pi/software/OPSORO-software/Scripts/restart_opsoro_service
sudo bash /home/pi/software/OPSORO-software/Scripts/restart_opsoro_service

sudo reboot

exit 0
