#!/bin/sh

OLD=onosw.sh

sudo service $OLD stop
sudo update-rc.d -f $OLD remove
sudo update-rc.d $OLD stop 80 0 1 2 3 4 5 6

sudo rm /etc/init.d/$OLD
sudo rm ../$OLD

sudo chmod +x setup_opsoro
./setup_opsoro
