#!/bin/sh

FOLDER=/home/pi/OPSORO/OS/
SERVICE=opsoro
STARTFILE=run

# Make sure we can run the script
sudo chmod +x $SERVICE

# Copy script to init for daemon
sudo cp $SERVICE /etc/init.d/$SERVICE
# Add service to startup
sudo update-rc.d $SERVICE defaults
sleep .5

# Make sure we can run the python script
sudo chmod +x $FOLDER$STARTFILE

# Start service
sudo service $SERVICE start
sleep .5
# Check service status
sudo service $SERVICE status
