#!/bin/sh

# stop opsoro service
# backup all files to seperate location (GIT pull is safe enough, we only keep this in case the user wants to revert)
# git pull
# restart opsoro service


sudo service opsoro stop

sudo mkdir /opsoro/previous/
sudo cp -r /opsoro/os/ /opsoro/previous/OS/

sudo git --git-dir=/opsoro/os/.git/ --work-tree=/opsoro/os/ remote update
sudo git --git-dir=/opsoro/os/.git/ --work-tree=/opsoro/os/ pull

# sudo chmod +x /opsoro/os/Scripts/restart_opsoro_service
sudo bash /opsoro/os/scripts/restart_opsoro_service

# sudo reboot

exit 0
